name: CI

on:
  pull_request:
    branches:
      - main
      - citest
    paths-ignore:
      - '**.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build the Plugin
        uses: docker://ssages/pysages-base:lastest
        with:
          entrypoint: python
          args: "-c 'import hoomd; print(hoomd.__version__)'"
