name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/pysages-base:latest

      - name: Build the Plugin
        run: |
          docker run -t pysages-base bash -c "mkdir build && cd build && cmake .. && make install"
